apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bot
  name: bot
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3000
  selector:
    io.kompose.service: bot
status:
  loadBalancer: {}
