apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: example-service
  name: example-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: example-service
    spec:
      containers:
      - env:
        - name: REGISTRY_ETCD_BASE
          value: /metrics-generator
        - name: REGISTRY_ETCD_URL
          value: http://example-etcd:2379
        - name: REGISTRY_SERVICE
          value: example-service
        image: abilioesteves/metrics-generator:latest
        name: example-service
        ports:
        - containerPort: 32865
        resources: {}
      restartPolicy: Always
status: {}
